version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/runner"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
